### ISSUE TITLE
Mutable definitions lead to dynlink errors

### ISSUE THREAD

**Issue by Janno** [SkySkimmer/coq-ltac2-compiler#14]
The README says mutable definitions are not compiled. IIUC everything should still work, it would just be "slower". Is that correct?

Here's my test case:
```
From Ltac2 Require Import Ltac2.
Ltac2 mutable mut : unit := ().
Ltac2 test () := match mut with () => () end.

From Ltac2Compiler Require Import Ltac2Compiler.
Ltac2 Compile test.
(*
Warning: Skipped compilation of mutable definitions mut [tac2compile-skipped-mutable,ltac2,default]

Dynlink error: execution of module initializers in the shared library failed: File "plugins/ltac2/tac2env.ml", line 79, characters 2-8: Assertion failed
*)
```

I am running 8.18.0.

I had mixed success with reproducing my original, much larger example. `Ltac2 Compile` would succeed if I did it in the same file where the mutable definition lives, but not if I ran it in another file. The example above replicates the error message but isn't derived from my actual example. I hope it's the same underlying issue.

**Comment by SkySkimmer** [comment]
>Ltac2 Compile would succeed if I did it in the same file where the mutable definition lives, but not if I ran it in another file.

That's rather strange. Do you have an example where it succeeds even though it seems like the bug should be triggered?

**Comment by Janno** [comment]
I do have an example but it's closed source. I'll try to minimize it more when I have some time.
