### ISSUE TITLE
OCaml does not support unicode binders?

### ISSUE THREAD

**Issue by Janno** [SkySkimmer/coq-ltac2-compiler#6]
Thanks for fixing #4 so quickly! I managed to compile quite a few functions already (so far with a 10% speedup in the one test file I am looking at) but I got stuck again at the next binder error:

```OCaml
File "/tmp/tac2compile_02742a/fdc8e1b.ml", line 2399, characters 30-31:
2399 |                         (let φ =
                                     ^
Error: Illegal character (\134)
```

**Comment by SkySkimmer** [comment]
Reference https://v2.ocaml.org/manual/lex.html#ident
`lowercase_ident = [a-z_][A-Za-z0-9_']*`
